name: Build spotifast Windows x64

on:
  workflow_dispatch:
  push:
    branches: [ master, main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout spotifast
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Install dependencies via vcpkg
        run: |
          vcpkg install glew:x64-windows-static projectm:x64-windows-static
          vcpkg integrate install

      - name: Build with MSBuild
        run: |
          msbuild spotifast.sln /p:Configuration=Release /p:Platform=x64

      - name: Prepare build artifacts
        shell: cmd
        run: |
          mkdir output
          dir /s /b *.exe
          for /r %%i in (spotifast.exe) do copy "%%i" output\

      - name: Upload spotifast artifact
        uses: actions/upload-artifact@v4
        with:
          name: spotifast-windows-x64
          path: output/
